import type { CaseFile, Citation, UploadedDoc } from "./types";

const dash = (v: string | null | undefined) => (v && v.trim() ? v : "— not yet provided");
const list = (items: string[], empty = "none") => (items.length ? items.map((i) => `- ${i}`).join("\n") : `- ${empty}`);

export function sourceLabel(c: Pick<Citation, "sourceType" | "synthetic" | "starterNote">): string {
  const parts = [c.sourceType === "public" ? "Official/public" : "Internal firm"];
  if (c.synthetic) parts.push("synthetic demo");
  if (c.starterNote) parts.push("starter note – verify");
  return parts.join(", ");
}

export function uniqueSources(citations: Citation[]): Citation[] {
  const seen = new Map<string, Citation>();
  for (const c of citations) if (!seen.has(c.docId)) seen.set(c.docId, c);
  // Public sources first, then firm.
  return [...seen.values()].sort((a, b) => (a.sourceType === b.sourceType ? 0 : a.sourceType === "public" ? -1 : 1));
}

/**
 * The adviser summary is assembled from the structured case file so every
 * field is exactly what the adviser saw in the live case panel. The model only
 * contributes the briefing, the action list and the email draft.
 */
export function composeSummary(opts: {
  caseFile: CaseFile;
  uploads: UploadedDoc[];
  briefing: string;
  nextActions: string[];
  email: string;
  sources: Citation[];
  /** Citations whose [S#] refs appear in briefing / nextActions. */
  briefingCitations: Citation[];
  generatedAt: string;
}): string {
  const c = opts.caseFile;
  const received = c.documentsReceived.length ? c.documentsReceived : opts.uploads.map((u) => `${u.name} – ${u.label}`);
  const sources = uniqueSources([...opts.briefingCitations, ...opts.sources]);
  // Rewrite per-request [S#] refs into the numbering of the RELEVANT SOURCES list.
  const refToNum = new Map(opts.briefingCitations.map((bc) => [bc.ref, sources.findIndex((s) => s.docId === bc.docId) + 1]));
  const renumber = (t: string) => t.replace(/\[(S\d+)\]/g, (m, ref) => (refToNum.has(ref) ? `[${refToNum.get(ref)}]` : ""));

  return `CLIENT CASE
Company: ${dash(c.companyName)}
Legal form: ${dash(c.legalForm)}
Incorporation date: ${dash(c.incorporationDate)}
Registered office: ${dash(c.registeredOffice)}
Requested services: ${c.requestedServices.length ? c.requestedServices.join("; ") : "— not yet provided"}
Employees: ${dash(c.employees)}
Payroll: ${dash(c.payrollRequirements)}
Bookkeeping software: ${dash(c.bookkeepingSoftware)}
Previous adviser: ${dash(c.previousAdviser)}
Tax registration status: ${dash(c.taxRegistrationStatus)}
Case category: ${dash(c.caseCategory)}
Priority: ${c.priority ? c.priority.toUpperCase() : "—"}${c.priorityReason ? ` – ${c.priorityReason}` : ""}

ADVISER BRIEFING
${renumber(opts.briefing)}

ESCALATION FLAGS
${list(c.escalations)}

DOCUMENTS RECEIVED
${list(received)}

MISSING DOCUMENTS
${list(c.missingDocuments)}

OPEN QUESTIONS
${list(c.openQuestions)}

RELEVANT SOURCES
${sources.length ? sources.map((s, i) => `[${i + 1}] (${sourceLabel(s)}) ${s.title}${s.url ? ` – ${s.url}` : ` – knowledge/${s.docId.replace(/__/g, "/")}`}`).join("\n") : "- none cited"}

RECOMMENDED NEXT ACTION
${opts.nextActions.map((a, i) => `${i + 1}. ${renumber(a)}`).join("\n")}

DRAFT CLIENT RESPONSE
${opts.email}

---
Generated by TaxHub on ${opts.generatedAt}. Intake summary for internal review – not tax advice. Verify all facts marked as starter notes against the official source.`;
}
